REM TEXT SCROLLER WITH EFFECTS

X=64
BY=-8
TXT$="WELCOME TO LOWRES CODER!"
TXTLEN=TEXT WIDTH(TXT$)+1

DO
  CLS 15

  REM DRAWS A UP AND DOWN MOVING BAR
  BR=BR+0.13
  BY=SIN(BR)*12+28
  COLOR 14
  BAR 0,BY TO 63,BY+7

  REM DRAWS SOME RANDOM PIXELS
  FOR I=1 TO 10
    PLOT RND*63,RND*61+1
  NEXT I

  REM DRAWS SCROLLING TEXT WITH SHADOW
  X=X-1
  COLOR 0
  TEXT X+1,30,TXT$
  COLOR 1
  TEXT X,29,TXT$

  REM RENDERS WAVE EFFECT
  SR=SR-0.2
  FOR SX=0 TO 63
    SCROLL SX,0 TO SX,63,0,SIN(SR+SX/128*PI)*16
  NEXT SX

  WAIT 0.04

  REM RESTARTS TEXT WHEN MOVED OUT OF SCREEN
  IF X<-TXTLEN THEN X=64
LOOP
